version: "0.5"

processes:
  api:
    command: "cd backend && composer dev"
    availability:
      restart: on_failure
      max_restarts: 5
  queue-worker:
    command: "cd backend && php artisan queue:work redis --queue=webhooks,default --sleep=1 --tries=3"
    availability:
      restart: on_failure
      max_restarts: 5
  website:
    command: "cd frontend && pnpm dev"
    availability:
      restart: on_failure
      max_restarts: 5
